### ISSUE TITLE
xcode 7 support

### ISSUE THREAD

**Issue by HarryF514** [JxbSir/JxbPgyerAssistant#4]
官方说：

> 对于 Xcode 开发者来说，将蒲公英的上传功能集成到 SDK 中可以大大方便应用的内测分发。蒲公英的用户提供了一款 Xcode 自动上传插件，该插件提供了应用的直接上传、二维码显示等功能。（暂不支持Xcode 7）

我想问，现在支持xcode7了么？

**Comment by JxbSir** [comment]
你好，老早支持了哦 

------------------ Original ------------------
